apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${deployment-name}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'git@github.com:${repo}.git'
    type: git
    path: apps
    targetRevision: '${branch}'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: '${gke-namespace}'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
