apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-secret-store
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cluster-secret-store
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: cluster-secret-store
    repoURL: https://nandotheessen1.github.io/cluster-secret-store/
    targetRevision: 0.1.0
    helm:
      parameters:
        - name: 'name'
          value: cluster-secret-store
        - name: 'projectId'
          value: ${project}
        - name: 'clusterLocation'
          value: ${region}
        - name: 'clusterName'
          value: ${cluster_name}
        - name: 'projectId'
          value: ${project}
        - name: 'serviceAccountName'
          value: ${kubernetes_service_account}
        - name: 'serviceAccountNamespace'
          value: ${kubernetes_service_account_namespace}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
