apiVersion: v1
kind: Secret
metadata:
  name: deployment
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:${platform_deployment_repo}.git
  sshPrivateKey: | 
    ${ssh_private_key}
