apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: docker-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: "{{ `{{ .docker_credentials }}` }}"
    name: docker-credentials
    creationPolicy: Owner
  data:
  - secretKey: docker_credentials
    remoteRef:
      key: {{ .Values.infrastructure.gcp.secret_manager.docker_credentials.name }}
      version: {{ .Values.infrastructure.gcp.secret_manager.docker_credentials.version | quote }}
