apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: docker-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: "{{ `{{ .docker }}` }}"
    name: docker-secret
    creationPolicy: Owner
  data:
  - secretKey: docker
    remoteRef:
      key: {{ .Values.infrastructure.gcp.secret_manager.docker.name }}
      version: {{ .Values.infrastructure.gcp.secret_manager.docker.version | quote }}
