#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: server-production
#spec:
#  replicas: 0
#  selector:
#    matchLabels:
#      app: server-production
#  template:
#    metadata:
#      name: server-production
#      labels:
#        app: server-production
#    spec:
#      containers:
#        - name: server-production
#          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
#          ports:
#              - containerPort: 80
#                name: http
#                protocol: TCP
#          workingDir: /opt/typedb-web
#          command: [
#            ./server,
#            --env=production,
#          ]
#          envFrom:
#            - secretRef:
#                name: server-secret
#      imagePullSecrets:
#        - name: docker-credentials
#---
#apiVersion: argoproj.io/v1alpha1
#kind: Rollout
#metadata:
#  name: server-production
#spec:
#  workloadRef:
#    apiVersion: apps/v1
#    kind: Deployment
#    name: server-production
#  replicas: {{ .Values.replica_count.production }}
#  revisionHistoryLimit: 2
#  strategy:
#    blueGreen:
#      activeService: server-production
#      previewService: server-production-preview
#      autoPromotionEnabled: false
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: server-production
#spec:
#  type: LoadBalancer
#  selector:
#    app: server-production
#  ports:
#    - protocol: TCP
#      port: 80
#      targetPort: http
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: server-production-preview
#spec:
#  type: LoadBalancer
#  selector:
#    app: server-production
#  ports:
#    - protocol: TCP
#      port: 80
#      targetPort: http
