apiVersion: v1
kind: ConfigMap
metadata:
  name: strapi-application-config
data:
  HOST: {{ .Values.application.strapi.host }}
  PORT: "1337"
  NODE_ENV: {{ .Values.application.strapi.node_env }}
  DATABASE_HOST: {{ .Values.db.host }}
  DATABASE_PORT: "3306"
  DATABASE_USERNAME: {{ .Values.db.credentials.username }}
  DATABASE_NAME: {{ .Values.db.database_name }}
