apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strapi-application
  template:
    metadata:
      name: strapi-application
      labels:
        app: strapi-application
    spec:
      containers:
        - name: strapi
          image: {{ .Values.application.strapi.image.repository }}:{{ .Values.application.strapi.image.tag }}
          ports:
              - containerPort: 1337
                name: http
          envFrom:
            - configMapRef:
                name: strapi-application-config
            - secretRef:
                name: strapi-application-secret
            - secretRef:
                name: strapi_application_db_password
      imagePullSecrets:
        - name: docker-credentials
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: strapi-application-config
data:
  HOST: {{ .Values.application.strapi.host }}
  PORT: "1337"
  NODE_ENV: {{ .Values.application.strapi.node_env }}
  DATABASE_HOST: {{ .Values.db.host }}
  DATABASE_PORT: "3306"
  DATABASE_USERNAME: {{ .Values.db.credentials.username }}
  DATABASE_NAME: {{ .Values.db.database_name }}
---
apiVersion: v1
kind: Secret
metadata:
  name: strapi-application-secret
type: Opaque
data:
  APP_KEYS: {{ .Values.application.strapi.credentials.app_keys }}
  API_TOKEN_SALT: {{ .Values.application.strapi.credentials.api_token_salt }}
  ADMIN_JWT_SECRET: {{ .Values.application.strapi.credentials.admin_jwt_secret }}
  JWT_SECRET: {{ .Values.application.strapi.credentials.jwt_secret }}
---
apiVersion: v1
kind: Service
metadata:
  name: strapi-application
spec:
  type: LoadBalancer
  selector:
    app: strapi-application
  ports:
    - protocol: TCP
      port: 1337
      targetPort: http
