apiVersion: v1
kind: Secret
metadata:
  name: strapi-application-secret
type: Opaque
data:
  APP_KEYS: {{ .Values.application.strapi.credentials.app_keys }}
  API_TOKEN_SALT: {{ .Values.application.strapi.credentials.api_token_salt }}
  ADMIN_JWT_SECRET: {{ .Values.application.strapi.credentials.admin_jwt_secret }}
  JWT_SECRET: {{ .Values.application.strapi.credentials.jwt_secret }}
  DATABASE_PASSWORD: {{ .Values.db.credentials.password }}
