apiVersion: v1
kind: Secret
metadata:
  name: strapi-db-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.db.credentials.root_password }}
  MYSQL_PASSWORD: {{ .Values.db.credentials.password }}
