apiVersion: v1
kind: Service
metadata:
  name: strapi-db
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: strapi-db
  ports:
    - name: strapi-db
      port: 3306
      targetPort: 3306
