apiVersion: v1
kind: Service
metadata:
  name: strapi-application
spec:
  type: NodePort
  selector:
    app: strapi-application
  ports:
    - name: http
      protocol: TCP
      port: 1337
      nodePort: 31337
      targetPort: http
