apiVersion: v1
kind: Service
metadata:
  name: strapi-application
spec:
  type: LoadBalancer
  selector:
    app: strapi-application
  ports:
    - protocol: TCP
      port: 1337
      targetPort: http
