apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strapi-application
  template:
    metadata:
      name: strapi-application
      labels:
        app: strapi-application
    spec:
      containers:
        - name: strapi
          image: {{ .Values.application.strapi.image.repository }}:{{ .Values.application.strapi.image.tag }}
          ports:
              - containerPort: 1337
                name: http
          envFrom:
            - configMapRef:
                name: strapi-application-config
            - secretRef:
                name: strapi-application-secrets
      imagePullSecrets:
        - name: docker-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: strapi-application
spec:
  type: LoadBalancer
  selector:
    app: strapi-application
  ports:
    - protocol: TCP
      port: 1337
      targetPort: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: strapi-application-config
data:
  HOST: {{ .Values.application.strapi.host }}
  PORT: "1337"
  NODE_ENV: {{ .Values.application.strapi.node_env }}
  DATABASE_HOST: {{ .Values.db.host }}
  DATABASE_PORT: "3306"
  DATABASE_USERNAME: {{ .Values.db.credentials.username }}
  DATABASE_NAME: {{ .Values.db.database_name }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: strapi-application-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    template:
      type: Opaque
      engineVersion: v2
      data:
        APP_KEYS: "{{ `{{ .app_keys }}` }}"
        API_TOKEN_SALT: "{{ `{{ .api_token_salt }}` }}"
        ADMIN_JWT_SECRET: "{{ `{{ .admin_jwt_secret }}` }}"
        JWT_SECRET: "{{ `{{ .jwt_secret }}` }}"
        DATABASE_PASSWORD: "{{ `{{ .db_password }}` }}"
    name: strapi-application-secrets
    creationPolicy: Owner
  data:
    - secretKey: app_keys
      remoteRef:
        key: {{ .Values.infrastructure.gcp.secret_manager.strapi_application_app_keys.name }}
        version: {{ .Values.infrastructure.gcp.secret_manager.strapi_application_app_keys.version | quote }}
    - secretKey: api_token_salt
      remoteRef:
        key: {{ .Values.infrastructure.gcp.secret_manager.strapi_application_api_token_salt.name }}
        version: {{ .Values.infrastructure.gcp.secret_manager.strapi_application_api_token_salt.version | quote }}
    - secretKey: admin_jwt_secret
      remoteRef:
        key: {{ .Values.infrastructure.gcp.secret_manager.strapi_application_admin_jwt_secret.name }}
        version: {{ .Values.infrastructure.gcp.secret_manager.strapi_application_admin_jwt_secret.version | quote }}
    - secretKey: jwt_secret
      remoteRef:
        key: {{ .Values.infrastructure.gcp.secret_manager.strapi_application_jwt_secret.name }}
        version: {{ .Values.infrastructure.gcp.secret_manager.strapi_application_jwt_secret.version | quote }}
    - secretKey: db_password
      remoteRef:
        key: {{ .Values.infrastructure.gcp.secret_manager.strapi_db_user_password.name }}
        version: {{ .Values.infrastructure.gcp.secret_manager.strapi_db_user_password.version | quote }}
