apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: strapi-db
spec:
  serviceName: "strapi-db"
  replicas: 1
  selector:
    matchLabels:
      app: strapi-db
  template:
    metadata:
      labels:
        app: strapi-db
    spec:
      containers:
        - name: strapi-db
          image: mysql:5.7
          securityContext:
            runAsUser: 1000
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 3306
              name: strapi-db
          envFrom:
            - configMapRef:
                name: strapi-db-config
            - secretRef:
                name: strapi_db_root_password
            - secretRef:
                name: strapi_db_user_password
          volumeMounts:
            - name: storage
              mountPath: /var/lib/strapi/db
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 20Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: strapi-db-config
data:
  MYSQL_USER: {{ .Values.db.credentials.username }}
  MYSQL_DATABASE: {{ .Values.db.database_name }}
---
apiVersion: v1
kind: Service
metadata:
  name: strapi-db
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: strapi-db
  ports:
    - name: strapi-db
      port: 3306
      targetPort: 3306
