config:
  dependencies:
    dependencies: [build]

build:
  correctness:
    build:
      image: graknlabs-ubuntu-20.04
      command: |
        bazel build //...

release:
  filter:
    owner: graknlabs
    branch: master
  deployment:
    deploy-artifact:
      image: graknlabs-ubuntu-20.04
      command: |
        export DEPLOY_ARTIFACT_USERNAME=$REPO_GRAKN_USERNAME
        export DEPLOY_ARTIFACT_PASSWORD=$REPO_GRAKN_PASSWORD
        bazel run --define version=(git rev-parse HEAD) //:deploy-web-main -- snapshot
    deploy-production:
      image: graknlabs-ubuntu-20.04
      dependencies: [deploy-artifact]
      command: |
        echo $NOMAD_CACERT_BASE64 | base64 -d > /tmp/nomad-ca.pem
        export NOMAD_CACERT=/tmp/nomad-ca.pem
        nomad job run infrastructure/web-main.nomad
