apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "${deployment.application-name}"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: typedb-web
    repoURL: https://repo.vaticle.com/repository/helm-snapshot/
    targetRevision: "${deployment.target-revision}"
    helm:
        parameters:
          - name: "infrastructure.gcp.project_id"
            value: "${infrastructure.gcp.project_id}"
          - name: "infrastructure.gcp.service_account_name"
            value: "${infrastructure.gcp.service_account_name}"
          - name: "infrastructure.gcp.secret_manager.docker_credentials.version"
            value: "${infrastructure.gcp.secret_manager.docker_credentials.version}"
          - name: "infrastructure.gcp.secret_manager.strapi_db_root_password.version"
            value: "${infrastructure.gcp.secret_manager.strapi_db_root_password.version}"
          - name: "infrastructure.gcp.secret_manager.strapi_db_user_password.version"
            value: "${infrastructure.gcp.secret_manager.strapi_db_user_password.version}"
          - name: "infrastructure.gcp.secret_manager.strapi_app_keys.version"
            value: "${infrastructure.gcp.secret_manager.strapi_app_keys.version}"
          - name: "infrastructure.gcp.secret_manager.strapi_api_token_salt.version"
            value: "${infrastructure.gcp.secret_manager.strapi_api_token_salt.version}"
          - name: "infrastructure.gcp.secret_manager.strapi_admin_jwt_token.version"
            value: "${infrastructure.gcp.secret_manager.strapi_admin_jwt_token.version}"
          - name: "infrastructure.gcp.secret_manager.strapi_jwt_token.version"
            value: "${infrastructure.gcp.secret_manager.strapi_jwt_token.version}"
          - name: "infrastructure.gke.name"
            value: "${infrastructure.gke.name}"
          - name: "infrastructure.gke.location"
            value: "${infrastructure.gke.location}"
          - name: "infrastructure.gke.service_account_name"
            value: "${infrastructure.gke.service_account_name}"
  destination:
    namespace: "${deployment.namespace}"
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
